### ISSUE TITLE
Failing when reading empty csv-files

### ISSUE THREAD

**Issue by FelixMoelder** [koesterlab/datavzrd#35]
Datavzrd currently fails without specific error message when reading a headerless/empty csv-file.
While empty files in general should not be passed this may happen when dynamically generating a datavzrd report and be handle accordingly.

When a empty-file is passed datavzrd fails reading the header (see [line 505](https://github.com/koesterlab/datavzrd/blob/b2acea58253461b6d22eefd589f405abca3c3e3a/src/render/portable/mod.rs#L505)) as this returns `None`.

Even when a header exists datavzrd fails ending up in an `unreachable!()`-arm (see [line 40](https://github.com/koesterlab/datavzrd/blob/b2acea58253461b6d22eefd589f405abca3c3e3a/src/render/portable/plot.rs#L40))

**Comment by fxwiegand** [comment]
There is still a problem when an empty file exists that has linkouts defined.
